### ISSUE TITLE
[功能建议] 希望 增加功能，可设置屏蔽/静止爬取一些站点rss

### ISSUE THREAD

**Issue by it985** [willow-god/Friend-Circle-Lite#44]
希望添加功能，可以设置不爬取友联的部分站点
例如我的
```yml
  - class_name: 加入的组织
    descr: 同类型的圈子，排名不分先后
    type: item
    suffix:
    link_list:
      - name: boringbay
        link: https://boringbay.com/
        descr: 无聊湾
        avatar: https://boringbay.com/api/icon/boringbay.com

      - name: 博客俱乐部
        link: https://www.blogsclub.org/
        descr: 我们的初衷是通过 BlogsClub 打造一个独立的个人博客集结地，旨在为博主们提供一个互相交流、学习和进步的空间，让博主们能够在这里共同分享彼此的经验和知识，共同进步。
        avatar: https://www.blogsclub.org/usr/themes/default/assets/images/logo_d.png

      - name: 博客我们
        link: https://blogwe.com/
        descr: 做更好的个人博客导航网站
        avatar: https://blogwe.com/content/templates/2025v1/static/picture/logo.png

      - name: 博客圈
        link: https://bokequan.cn/
        descr: 致力于个人独立博客
        avatar: https://bokequan.cn/wp-content/uploads/2024/10/1730017568-1712562465bokequan.png

      - name: 博客录
        link: https://boke.lu/
        descr: 博客收录展示平台
        avatar: https://boke.lu/%E5%8D%9A%E5%AE%A2%E5%BD%95logo%E5%9B%9B%E7%89%88%E5%8A%A0%E5%AE%BD%E7%89%88%E7%99%BD1-70k.png

      - name: 博友圈
        link: https://www.boyouquan.com/home
        descr: 博客人的朋友圈，博客收录与文章 RSS 聚合网站。
        avatar: https://www.boyouquan.com/assets/images/sites/logo/planet-shuttle.png

      - name: BlogFinder
        link: https://bf.zzxworld.com/
        descr: 发现优秀的个人博客
        avatar: https://bf.zzxworld.com/images/logo-v2.png

      - name: 笔墨迹
        link: https://blogscn.fun
        descr: 致敬还在写博客的我们！
        avatar: https://photo.xiangming.site/img/blogscn_icon.png
```
还有其他的，如资讯类或者云服务类
